Repository DDD-4/Synesthesia-Android, pull requests merged in 2020-09, with the labels that each got.

#22 Home Sort 화면 추가
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/di/module/AppModule.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeSortDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeSortViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/sort/SortSetting.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/sort/SortType.kt
  app/src/main/res/drawable/background_dialog_white_round_20.xml
  app/src/main/res/drawable/ic_arrow_drop_down.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_bottom_sort.xml
  app/src/main/res/layout/layout_home_contents.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#23 refactor : 내정보 UI - 모션 레이아웃 적용
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/xml/secen_my_page.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: refactor

#25 Feature/star rating dialog
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/base/BaseBottomSheetDialogFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/StarRatingBottomDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/viewmodel/StarRatingViewModel.kt
  app/src/main/res/drawable/background_white_stroke_dadada.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/layout_bottom_star_rating.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#26 api 기초 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Beer.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Comment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/RateOwner.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Related.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/RelatedBeers.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Response.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Result.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Review.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/BeerApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/di/module/NetworkModule.kt
  app/src/main/java/com/ddd4/synesthesia/beer/di/module/RepositoryModule.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/layout_home_contents.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/PropertiesExt.kt
Labels: refactor

#27 Feature/related
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Related.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/RelatedBeers.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Result.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/splash/view/SplashActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/RecyclerItemDecoration.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/layout_beer_card.xml
  app/src/main/res/layout/layout_bottom_star_rating.xml
  app/src/main/res/layout/layout_detail_contents.xml
  app/src/main/res/values/interger.xml
  app/src/main/res/values/strings.xml
Labels: feature, refactor

#28 Feature/home refactor
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/ext/ViewExt.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/NavigationDirections.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeSortDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/sort/SortType.kt
  app/src/main/res/drawable/background_dialog_round_20.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/layout_bottom_sort.xml
  app/src/main/res/navigation/home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: refactor

#34 Feature/user info
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Beer.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Response.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Result.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/User.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/BeerApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/WriteNickNameActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/ItemClickListener.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_modify.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_write_nickname.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/layout_home_header.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/secen_my_page.xml
Labels: feature, refactor
