Repository DDD-4/Synesthesia-Android, pull requests merged in 2020-10, with the labels that each got.

#36 Feature/already review
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/ReviewOwner.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/StarRatingBottomDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/WriteReviewActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/viewmodel/StarRatingViewModel.kt
  app/src/main/res/layout/activity_write_review.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/layout_beer_card.xml
  app/src/main/res/layout/layout_bottom_star_rating.xml
  app/src/main/res/layout/layout_home_header.xml
  app/src/main/res/layout/layout_my_page.xml
  app/src/main/res/layout/layout_rate.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/interger.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, refactor

#37 Feature/home filter
  app/build.gradle.kts
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/BeerApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/di/module/AppModule.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/adapter/FilterCountryAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/FilterDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/FilterViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/MutableLiveDataList.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/filter/BeerFilter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/filter/FilterImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/filter/FilterSetting.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/sort/SortType.kt
  app/src/main/res/color/filter_select_change.xml
  app/src/main/res/drawable-hdpi/btn_radio.png
  app/src/main/res/drawable-hdpi/btn_radio_active.png
  app/src/main/res/drawable-mdpi/btn_radio.png
  app/src/main/res/drawable-mdpi/btn_radio_active.png
  app/src/main/res/drawable-xhdpi/btn_radio.png
  app/src/main/res/drawable-xhdpi/btn_radio_active.png
  app/src/main/res/drawable-xxhdpi/btn_radio.png
  app/src/main/res/drawable-xxhdpi/btn_radio_active.png
  app/src/main/res/drawable-xxxhdpi/btn_radio.png
  app/src/main/res/drawable-xxxhdpi/btn_radio_active.png
  app/src/main/res/drawable/country_selector.xml
  app/src/main/res/drawable/ic_chip_cancel_24.xml
  app/src/main/res/drawable/ic_seekbar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_filter_country.xml
  app/src/main/res/layout/layout_filter.xml
  app/src/main/res/layout/layout_filter_chip.xml
  app/src/main/res/layout/layout_home_filter_chip.xml
  app/src/main/res/layout/layout_home_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: feature

#39 feat : 홈화면 맥주 리스트 페이지네이션 기능 추가
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Response.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/BeerApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/EndlessRecyclerViewScrollListener.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_home_contents.xml
Labels: feature, refactor

#40 refactor : 제플린 디자인 가이드 적용
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/WriteNickNameActivity.kt
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/layout/activity_write_nickname.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/layout_beer_card.xml
  app/src/main/res/layout/layout_global_toolbar.xml
  app/src/main/res/xml/secen_my_page.xml
Labels: refactor

#41 feat : 리뷰 전체 보기 UI 추가
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Review.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/BeerApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/review/view/ReviewAllFragment.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/layout_global_toolbar.xml
  app/src/main/res/layout/layout_rate.xml
  app/src/main/res/layout/layout_review.xml
  app/src/main/res/navigation/home.xml
Labels: feature

#42 Feature/my review
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/Results.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/local/InfomationsData.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/BeerApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/DetailFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/review/view/MyReviewFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/review/viewmodel/MyReviewViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_my_review.xml
  app/src/main/res/layout/layout_my_review.xml
  app/src/main/res/navigation/home.xml
  app/src/main/res/values/strings.xml
Labels: feature

#43 Feature/app-config
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/AppConfig.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/BeerRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/BeerApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/BeerRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/FilterDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/FilterViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
Labels: feature

#44 fix : 닉네임 변경 UI에 기존 등록된 닉네임이 입력되도록 수정
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/MyPageFragment.kt
Labels: bug

#45 Feature/home design
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_btn_dropdown.xml
  app/src/main/res/drawable/ic_rating_star.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/chip_home_item.xml
Labels: bug, refactor

#47 refactor : 마이페이지 디자인 가이드 적용
  app/src/main/java/com/ddd4/synesthesia/beer/ext/FloatExt.kt
  app/src/main/java/com/ddd4/synesthesia/beer/ext/IntExt.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/res/drawable/arrow_right_baseline.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/layout/activity_write_nickname.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/layout_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/interger.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/secen_my_page.xml
Labels: refactor

#48 Feature/filter clear
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/adapter/FilterCountryAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/FilterDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/FilterViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/MutableLiveDataList.kt
  app/src/main/res/drawable/ic_reset_24.xml
  app/src/main/res/layout/layout_filter.xml
  app/src/main/res/values/styles.xml
Labels: bug, feature

#49 refactor : 스플래쉬, 앱 아이콘 변경
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/ddd4/synesthesia/beer/ext/ImageViewExt.kt
  app/src/main/res/drawable/beer.png
  app/src/main/res/drawable/drawable-hdpi/logo.jpg
  app/src/main/res/drawable/drawable-hdpi/logo.png
  app/src/main/res/drawable/drawable-mdpi/logo.jpg
  app/src/main/res/drawable/drawable-mdpi/logo.png
  app/src/main/res/drawable/drawable-xhdpi/logo.jpg
  app/src/main/res/drawable/drawable-xhdpi/logo.png
  app/src/main/res/drawable/drawable-xxhdpi/logo.jpg
  app/src/main/res/drawable/drawable-xxhdpi/logo.png
  app/src/main/res/drawable/drawable-xxxhdpi/logo.jpg
  app/src/main/res/drawable/drawable-xxxhdpi/logo.png
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/layout_beer_card.xml
  app/src/main/res/layout/layout_home_header.xml
  app/src/main/res/layout/layout_my_review.xml
  app/src/main/res/layout/layout_rate.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#50 Feature/login refactoring
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/KakaoApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/remote/service/KakaoAuthApi.kt
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/response/TokenResponse.kt
  app/src/main/java/com/ddd4/synesthesia/beer/di/module/NetworkModule.kt
  app/src/main/java/com/ddd4/synesthesia/beer/di/module/RepositoryModule.kt
  app/src/main/java/com/ddd4/synesthesia/beer/domain/repository/LoginRepository.kt
  app/src/main/java/com/ddd4/synesthesia/beer/ext/ImageViewExt.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/base/BaseActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/base/BaseApplication.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/StarRatingBottomDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/splash/view/SplashActivity.kt
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/layout_beer_card.xml
  app/src/main/res/layout/layout_my_review.xml
  app/src/main/res/xml/secen_my_page.xml
Labels: refactor

#52 Feature/filter design
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/FilterDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/CustomTypefaceSpan.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_fiter_line.xml
  app/src/main/res/drawable/layer_filter_line.xml
  app/src/main/res/layout/layout_filter.xml
  app/src/main/res/layout/layout_filter_aroma_chip.xml
  app/src/main/res/layout/layout_filter_style_chip.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: bug, refactor

#54 refactor : 디자인 상세 디테일 수정
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/FilterDialog.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/layout_beer_card.xml
  app/src/main/res/layout/layout_detail_contents.xml
  app/src/main/res/layout/layout_filter.xml
  app/src/main/res/layout/layout_review.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/secen_my_page.xml
Labels: refactor

#55 refactor : 내가 작성한 리뷰 디자인 디테일 수정
  app/src/main/java/com/ddd4/synesthesia/beer/data/model/ReviewOwner.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/StarRatingBottomDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/detail/view/WriteReviewActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/FilterDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/WriteNickNameActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/CustomAlertDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/ItemClickListener.kt
  app/src/main/res/layout/activity_write_nickname.xml
  app/src/main/res/layout/activity_write_review.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/layout_bottom_star_rating.xml
  app/src/main/res/layout/layout_my_review.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: refactor

#56 Feature/reset refactor
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/FilterDialog.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/viewmodel/FilterViewModel.kt
  app/src/main/res/layout/layout_home_header.xml
Labels: refactor

#57 fix: 홈 아이템의 향표기 Chip 부분 상단 컴포넌트와의 마진값 조절
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/res/layout/item_home.xml
Labels: refactor

#61 refactor : 전체 뷰 디자인 가이드 적용2
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/res/layout/layout_filter.xml
  app/src/main/res/layout/layout_home_header.xml
  app/src/main/res/layout/layout_rate.xml
  app/src/main/res/raw/home_motion.gif
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#62 feat : Firebase Crashlytics 추가
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: feature

#65 Feature/refactoring
  app/src/main/java/com/ddd4/synesthesia/beer/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/ddd4/synesthesia/beer/ext/AppCompatActivityExt.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/login/view/LoginActivity.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/splash/view/SplashActivity.kt
  app/src/main/res/drawable/ic_img_profile_blank.xml
  app/src/main/res/drawable/ic_kakao_login.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/layout_beer.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: refactor

#66 Feature/home refactor
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/ddd4/synesthesia/beer/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_btn_filter.xml
  app/src/main/res/drawable/ic_img_blank.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_empty_list.xml
  app/src/main/res/layout/layout_home_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#68 fix : 프로필 없이 로그인 시도시 앱 종료되는 현상 수정
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/login/view/LoginActivity.kt
Labels: bug

#69 refactor : 연결끊기 -> 회원탈퇴 수정
  app/src/main/java/com/ddd4/synesthesia/beer/data/source/local/InfomationsData.kt
  app/src/main/java/com/ddd4/synesthesia/beer/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/secen_my_page.xml
Labels: refactor
